# Generated by Django 5.2.3 on 2025-07-04 14:56

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_client',
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', accounts.models.PersonManager()),
            ],
        ),
    ]
