# Generated by Django 5.2.4 on 2025-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
